# Generated by Django 4.2.6 on 2023-10-26 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(default='logo.png', upload_to='uploads/images'),
        ),
    ]
